case(RUBY_VERSION)

when "2.2.5" then
  appraise "capybara-3.0-ruby#{RUBY_VERSION}" do
    gem 'capybara', '~> 3.0.2'
  end
when "2.3.3" then
  appraise "capybara-3.0-ruby#{RUBY_VERSION}" do
    gem 'capybara', '~> 3.0.2'
  end
end
