checks:
    ruby:
        style_global_vars: true
        style_flip_flop: true
        style_file_name: true
        style_even_odd: true
        style_end_of_line: true
        style_empty_literal: true
        style_each_with_object: true
        style_constant_name: true
        style_class_methods: true
        style_class_check:
            enforced_style: 'is_a?'
        style_class_and_module_camel_case: true
        style_block_comments: true
        style_ascii_identifiers: true
        style_ascii_comments: true
        style_array_join: true
        style_and_or: true
        style_alias: true
        style_accessor_method_name: true
        smell_line_length:
            max: '4'
        smell_block_nesting:
            max: '3'
        rails_validation: true
        rails_read_write_attribute: true
        rails_has_and_belongs_to_many: true
        rails_foreach: true
        rails_find_by: true
        rails_delegate: true
        rails_default_scope: true
        lint_void: true
        lint_useless_setter_call: true
        lint_useless_else_without_rescue: true
        lint_useless_comparison: true
        lint_useless_assignment: true
        lint_useless_access_modifier: true
        lint_unused_method_argument: true
        lint_unused_block_argument: true
        lint_underscore_prefixed_variable_name: true
        lint_string_conversion_in_interpolation: true
        lint_loop: true
        lint_literal_in_interpolation: true
        lint_literal_in_condition: true
    javascript:
        yoda:
            setting: 'Disallow Yoda Conditions'
        wrap_regex: true
        wrap_iife: true
        vars_on_top: true
        valid_typeof: true
        valid_jsdoc: true
        use_isnan: true
        space_return_throw_case: true
        radix: true
        one_var: true
        no_wrap_func: true
        no_with: true
        no_void: true
        no_var: true
        no_use_before_define: true
        no_unused_vars: true
        no_unused_expressions: true
        no_unreachable: true
        no_underscore_dangle: true
        no_undefined: true
        no_undef_init: true
        no_undef: true
        no_trailing_spaces: true
        no_ternary: true
        no_sync: true
        no_sparse_arrays: true
        no_space_before_semi: true
        no_shadow_restricted_names: true
        no_shadow: true
        no_sequences: true
        no_self_compare: true
        no_script_url: true
        no_return_assign: true
        no_reserved_keys: true
        no_redeclare: true
        no_proto: true
        no_process_exit: true
        no_process_env: true
        no_plusplus: true
        no_path_concat: true
        no_octal_escape: true
        no_octal: true
        no_obj_calls: true
        no_new_wrappers: true
        no_new_require: true
        no_new_object: true
        no_new_func: true
        no_new: true
        no_nested_ternary: true
        no_negated_in_lhs: true
        no_native_reassign: true
        no_multi_str: true
        no_mixed_spaces_and_tabs: true
        no_loop_func: true
        no_lonely_if: true
        no_lone_blocks: true
        no_labels: true
        no_label_var: true
        no_irregular_whitespace: true
        no_iterator: true
        no_invalid_regexp: true
        no_inner_declarations: true
        no_inline_comments: true
        no_implied_eval: true
        no_func_assign: true
        no_floating_decimal: true
        no_fallthrough: true
        no_extra_strict: true
        no_extra_semi: true
        no_extra_boolean_cast: true
        no_extra_bind: true
        no_extend_native: true
        no_ex_assign: true
        no_eval: true
        no_eq_null: true
        no_empty_label: true
        no_empty_class: true
        no_empty: true
        no_else_return: true
        no_dupe_keys: true
        no_div_regex: true
        no_delete_var: true
        no_debugger: true
        no_control_regex: true
        no_constant_condition: true
        no_console: true
        no_comma_dangle: true
        no_catch_shadow: true
        no_caller: true
        no_bitwise: true
        no_array_constructor: true
        no_alert: true
        new_parens: true
        new_cap: true
        guard_for_in: true
        func_names: true
        eqeqeq: true
        eol_last: true
        dot_notation: true
        default_case: true
        curly: true
        consistent_this: true
        consistent_return: true
        comma_style:
            style: 'At the end of the line'
        camelcase: true
        block_scoped_var: true

filter:
    excluded_paths:
        - 'test/*'

tools:
    external_code_coverage: true