source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.4'

# Use sqlite3 as the database for Active Record
gem 'sqlite3', '1.3.11'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.2'
gem 'jquery-rails', '3.1.4'

gem "selenium-webdriver", "~> 2.53.0"
gem "mocha", "0.13.3", :require => false
gem "appraisal", "~> 0.5.1"

gem 'ae_page_objects', :path => "../../../.."

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks', '2.5.3'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

gem 'forum', :path => "engines"

