source "https://rubygems.org"

gem "rails", "3.1.12"
gem "sqlite3"
gem 'jquery-rails'

group :development do
  gem 'rubyzip', '< 1.0.0'
  gem 'ae_page_objects', :path => '../../..'
  gem "mocha", "0.13.3", :require => false
end
