source "https://rubygems.org"

gem "rails", "3.1.12"
gem 'sqlite3', '1.3.11'
gem 'jquery-rails', '3.1.4'

gem "selenium-webdriver", "~> 2.53.0"
gem "mocha", "0.13.3", :require => false
gem "appraisal", "~> 2.0"

gem 'ae_page_objects', :path => "../../.."

gem 'forum', :path => "engines"

gem 'rake', '~> 11.0'

gem 'mime-types', '< 3'
gem "rack", "< 2"
gem "public_suffix", "~> 1.4.6"
gem "nokogiri", "~> 1.6.8"
