# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require 'rake/testtask.rb'
require_relative 'config/application'

Rails.application.load_tasks

namespace :test do
  Rake::TestTask.new(:selenium) do |t|
    t.libs << 'test'
    t.pattern = 'test/selenium/**/*_test.rb'
    t.verbose = true

    if t.respond_to?(:warning=)
      t.warning = false
    end
  end
end
