case(RUBY_VERSION)
when '1.9.3' then

  appraise "capybara-1.1-ruby#{RUBY_VERSION}" do
    gem 'capybara', '~> 1.1.4'
  end

  appraise "capybara-2.1-ruby#{RUBY_VERSION}" do
    gem 'capybara', '~> 2.1.0'
  end

  appraise "capybara-2.2-ruby#{RUBY_VERSION}" do
    gem 'capybara', '~> 2.2.0'
  end

when '2.0.0', '2.1.2', '2.2.0', '2.3.0' then

  appraise "capybara-2.1-ruby#{RUBY_VERSION}" do
    gem 'capybara', '~> 2.1.0'
  end

  appraise "capybara-2.2-ruby#{RUBY_VERSION}" do
    gem 'capybara', '~> 2.2.0'
  end

end
