case(RUBY_VERSION)
when "2.2.5" then

  appraise "capybara-1.1-ruby#{RUBY_VERSION}" do
    gem "capybara", "~> 1.1.4"
  end

  appraise "capybara-2.1-ruby#{RUBY_VERSION}" do
    gem "capybara", "~> 2.1.0"
  end

  appraise "capybara-2.2-ruby#{RUBY_VERSION}" do
    gem "capybara", "~> 2.2.0"
  end

  appraise "capybara-2.3-ruby#{RUBY_VERSION}" do
    gem 'capybara', '~> 2.3.0'
  end

  appraise "capybara-2.4-ruby#{RUBY_VERSION}" do
    gem 'capybara', '~> 2.4.0'
  end

  appraise "capybara-2.5-ruby#{RUBY_VERSION}" do
    gem 'capybara', '~> 2.5.0'
  end

  appraise "capybara-2.6-ruby#{RUBY_VERSION}" do
    gem 'capybara', '~> 2.6.0'
  end

  appraise "capybara-2.7-ruby#{RUBY_VERSION}" do
    gem 'capybara', '~> 2.7.0'
  end

end
