source "https://rubygems.org"

gem 'rails', '2.3.18'
gem 'sqlite3'
gem 'rake'
gem 'rdoc'

gem "selenium-webdriver"
gem "mocha", "0.9.7"
gem "appraisal", "~> 0.5.1"

gem 'ae_page_objects', :path => "../../../.."

if RUBY_VERSION =~ /\A1\.8/
  gem 'capybara', '~> 1.1.4'
  gem "nokogiri", "< 1.6.0"
  gem 'rubyzip', '< 1.0.0'
  gem 'mime-types', '< 2'
end

if RUBY_VERSION =~ /\A1\.9/
  gem 'mime-types', '< 3'
end
