source "https://rubygems.org"

gem 'rails', '2.3.18'
gem 'rake', '0.8.3'
gem 'sqlite3'

group :development do
  gem 'ae_page_objects', :path => '../../..'
  gem "mocha", "0.13.3", :require => false
end
