source "https://rubygems.org"

gem 'rails', '2.3.18'
gem 'sqlite3'
gem 'rdoc'

gem "selenium-webdriver"
gem "mocha", "0.9.7"
gem "appraisal", "~> 0.5.1"

gem 'ae_page_objects', :path => "../../../.."

gem 'rake', '~> 11.0'

gem 'mime-types', '< 3'
