source "https://rubygems.org"

gem "rails",    '3.2.13'
gem 'sqlite3', '1.3.11'
gem 'jquery-rails', '3.1.4'

gem "selenium-webdriver", "~> 2.53.0"
gem "mocha", "0.13.3", :require => false
gem "appraisal", "~> 0.5.1"

gem 'ae_page_objects', :path => "../../../.."

gem 'forum', :path => "../engines"

gem 'rake', '~> 11.0'

if RUBY_VERSION =~ /\A1\.9/
  gem 'mime-types', '< 3'
end

if RUBY_VERSION =~ /\A2\.2/
  gem 'test-unit'
end
