source "https://rubygems.org"

gem "rails",    '3.2.0'
gem "sqlite3"
gem 'jquery-rails'

group :development do
  gem 'ae_page_objects', :path => '../../..'
  gem "mocha", "0.13.3", :require => false
  gem "rcov", ">= 0"
end
