case(RUBY_VERSION)
when '1.8.7' then

  appraise "capybara-1.1-ruby#{RUBY_VERSION}" do
    gem 'capybara', '~> 1.1.4'
  end

when '1.9.3' then

  appraise "capybara-1.1-ruby#{RUBY_VERSION}" do
    gem 'capybara', '~> 1.1.4'
  end

  appraise "capybara-2.1-ruby#{RUBY_VERSION}" do
    gem 'capybara', '~> 2.1.0'
  end

  appraise "capybara-2.2-ruby#{RUBY_VERSION}" do
    gem 'capybara', '~> 2.2.0'
  end

end
