source "https://rubygems.org"

gem 'rails', '3.0.20'
gem 'sqlite3'
gem 'jquery-rails'

gem "nokogiri", "< 1.6.0"

group :development do
  gem 'rubyzip', '< 1.0.0'
  gem 'ae_page_objects', :path => '../../..'
  gem "mocha", "0.13.3", :require => false
end
