source "https://rubygems.org"

gem 'rails', '3.0.20'
gem 'sqlite3'
gem 'jquery-rails'

gem "selenium-webdriver"
gem "mocha", "0.13.3", :require => false
gem "appraisal", "~> 0.5.1"

gem 'ae_page_objects', :path => "../../../.."

if RUBY_VERSION =~ /\A1\.8/
  gem 'capybara', '~> 1.1.4'
  gem "nokogiri", "< 1.6.0"
  gem 'rubyzip', '< 1.0.0'
  gem 'mime-types', '< 2'
end
